services:
  support-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../support.db:/app/support.db
    environment:
      - ENV=development
